---
title: "Ferrum_Temporal Analysis"
output: html_document
date: "2025-03-14"
editor_options: 
  chunk_output_type: console
---

# Load Packages
```{r}
#install.packages("dataRetrieval")
library(dataRetrieval)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(PLS205)
library(lubridate)
library(emmeans)
library(lme4)
library(ggeasy)
library(lattice)
library(rstatix)
library(ggsignif)
library(outliers)
library(ggpmisc)
library(ggpubr)
library(r2symbols)
library(stargazer)
library(ggbreak)
library(writexl)
library(ggrepel)
library(stringr)
library(ggthemes)
library(reshape)
library(RColorBrewer)
library(readxl)
library(dplyr)
library(gridExtra)
library(scales)
library(dbscan)
library(mclust)
library(devtools)
library(factoextra)
library(corrplot)
library(ggbiplot)
library(ggcorrplot)
library(GGally)
library(Hmisc)
library(ggbiplot)
library(ggfortify)
library(emmeans)
library(lme4)
library(lmerTest)
library(multcomp)
library(PLS205)
library(readxl)
library(learnr)
library(scatterplot3d)
library(vegan)
library(ggtern)
library(plotrix)
library(smwrBase)
library(smwrData)
library(smwrGraphs)
library(colorBlindness)
library(flextable)
library(officer)
library(dunn.test)
library(multcompView)
library(patchwork)
library(ggpattern)
```

# Download Discharge Data
```{r}
# Set site numbers for the 4 water stations we want to pull data for
site_numbers <- c("15564879", "15743850", "15744500", "15747000")

sites <- whatNWISsites(sites = site_numbers)

view(sites)

write_xlsx(sites, "C:/Users/tayta/Downloads/USGS water stations.xlsx")

# Define the time period
start_date <- "2015-01-01"
end_date <- "2024-12-31"

# Retrieve daily discharge data for all sites
discharge_data <- readNWISdv(
  siteNumbers = site_numbers, 
  parameterCd = "00060", 
  startDate = start_date, 
  endDate = end_date
)

# add site names to site numbers
site_names <- sites %>% 
  dplyr::select(site_no, station_nm)

discharge_data <- left_join(discharge_data, site_names, by = join_by(site_no))

discharge_data <- discharge_data %>%
  mutate(Year = year(Date)) %>%
  dplyr::rename(discharge_cfs = X_00060_00003)

# plot the Q data
library(ggplot2)

q.p <- ggplot(discharge_data, aes(x = Date, y = discharge_cfs, color = station_nm)) +
  geom_line() +
  facet_wrap(station_nm~., scales = "free", ncol = 2)+
  labs(x = "Date",
       y = "Discharge (cfs)") +
  theme_minimal() +
  theme(
    legend.position = "none"
  )

q.p

ggsave(q.p, filename = "02_Hydrographs_Available_Data_2015to2025.png",
       width = 11, height = 7)
```

```{r}


str(discharge_data)

discharge_summary <- discharge_data %>%
  mutate(Period = case_when(
    Year >= 2000 & Year <= 2018 ~ "2000-2018",
    Year >= 2019 & Year <= 2024 ~ "2019-2024",
    TRUE ~ NA_character_  # Assign NA to other years
  )) %>%
  filter(!is.na(Period)) %>%  # Filter only for relevant periods
  group_by(station_nm, Period) %>%
  summarise(
    Mean_Discharge = round(mean(discharge_cfs, na.rm = TRUE), 2),
    SD_Discharge = round(sd(discharge_cfs, na.rm = TRUE), 2),
    .groups = "drop"
  )

view(discharge_summary)

discharge_summary_wide <- discharge_summary %>%
  dplyr::select(-SD_Discharge) %>%
  pivot_wider(
    names_from = Period,
    values_from = Mean_Discharge
  ) %>%
  mutate(difference = .[[3]] - .[[2]])

view(discharge_summary_wide)

write_xlsx(discharge_summary_wide, "C:/Users/tayta/Downloads/Brooks Range Pre and Post Discharge Averages.xlsx")
```



```{r}
# Download data from Wulik station
wulik <- "15747000"

# Define the time period
start_date <- "2000-01-01"
end_date <- "2024-12-31"

# Retrieve daily discharge data for all sites
wulik_discharge_data <- readNWISdv(
  siteNumbers = wulik, 
  parameterCd = "00060", 
  startDate = start_date, 
  endDate = end_date
)

wulik_discharge_data <- wulik_discharge_data %>%
  mutate(Year = year(Date)) %>%
  dplyr::rename(discharge_cfs = X_00060_00003)

# Create period groups and summarize
discharge_summary <- wulik_discharge_data %>%
  mutate(Period = case_when(
    Year >= 2000 & Year <= 2018 ~ "2000-2018",
    Year >= 2019 & Year <= 2024 ~ "2019-2024",
    TRUE ~ NA_character_  # Assign NA to other years
  )) %>%
  filter(!is.na(Period)) %>%  # Filter only for relevant periods
  summarise(
    Mean_Discharge = round(mean(discharge_cfs, na.rm = TRUE), 2),
    SD_Discharge = round(sd(discharge_cfs, na.rm = TRUE), 2),
    .by = Period
  )

view(discharge_summary)

write_xlsx(wulik_discharge_data, "C:/Users/tayta/Downloads/raw Wulik Discharge.xlsx")
write_xlsx(discharge_summary, "C:/Users/tayta/Downloads/Wulik Discharge Summary.xlsx")
```

```{r}
# Download data from Wulik station
Kobuk <- "15744500"

# Define the time period
start_date <- "2000-01-01"
end_date <- "2024-12-31"

# Retrieve daily discharge data for all sites
Kobuk_discharge_data <- readNWISdv(
  siteNumbers = Kobuk, 
  parameterCd = "00060", 
  startDate = start_date, 
  endDate = end_date
)

Kobuk_discharge_data <- Kobuk_discharge_data %>%
  mutate(Year = year(Date)) %>%
  dplyr::rename(discharge_cfs = X_00060_00003)

# Create period groups and summarize
Kobuk_discharge_summary <- Kobuk_discharge_data %>%
  mutate(Period = case_when(
    Year >= 2000 & Year <= 2018 ~ "2000-2018",
    Year >= 2019 & Year <= 2024 ~ "2019-2024",
    TRUE ~ NA_character_  # Assign NA to other years
  )) %>%
  filter(!is.na(Period)) %>%  # Filter only for relevant periods
  summarise(
    Mean_Discharge = round(mean(discharge_cfs, na.rm = TRUE), 2),
    SD_Discharge = round(sd(discharge_cfs, na.rm = TRUE), 2),
    .by = Period
  )

view(Kobuk_discharge_summary)

write_xlsx(Kobuk_discharge_data, "C:/Users/tayta/Downloads/raw Kobuk Discharge.xlsx")
write_xlsx(Kobuk_discharge_summary, "C:/Users/tayta/Downloads/Kobuk Discharge Summary.xlsx")
```

```{r}
Wulik_q.p <- ggplot(wulik_discharge_data, aes(x = Date, y = X_00060_00003, color = site_no)) +
  geom_line() +
  #facet_grid(station_nm~., scales = "free")+
  labs(x = "Date",
       y = "Discharge (cfs)") +
  theme_minimal()

Wulik_q.p
```

# LOad Aggie Data
```{r}
Agashashok_River_Data <- read_excel("C:/Users/tevinger/Box/Poulin Lab ETOX/Project Folders/Alaska BITE_HEAT (Taylor Evinger)/Evinger Manuscripts/Ferrum Manuscript/Datasheets/Ferrum Manuscript Datasheets/Agashashok_Temporal_Data.xlsx")
View(Agashashok_River_Data)
```

## Add column for year and season
```{r}
Agashashok_River_Data <- Agashashok_River_Data %>%
mutate(
    sample_collection_year = year(as.Date(sample_collection_date_mm_dd_yy)),
    sample_collection_month = month(as.Date(sample_collection_date_mm_dd_yy), label = TRUE, abbr = FALSE)
  ) %>%
  mutate(
    sample_collection_season = case_when(
      sample_collection_month %in% c("May", "June") ~ "early",
      sample_collection_month == "July" ~ "middle",
      sample_collection_month %in% c("August", "September") ~ "late",
      TRUE ~ NA_character_
    )
  ) %>%
  relocate(sample_collection_year, sample_collection_month, sample_collection_season, .after = SamplingEventID)

View(Agashashok_River_Data)
```

```{r}
Aggie_SiteID_counts <- Agashashok_River_Data %>%
  count(SiteID_mod, name = "SiteID_total_count")

view(Aggie_SiteID_counts)


Agashashok_River_Data_with_counts <- Agashashok_River_Data %>%
 left_join(Aggie_SiteID_counts, by = "SiteID_mod") %>%
  relocate(SiteID_total_count, .after = SiteID_mod)

view(Agashashok_River_Data_with_counts)

# select site Id's that have been sampled at least 5 times
Agashashok_River_Data_filtered <- Agashashok_River_Data_with_counts %>%
  filter(SiteID_total_count > 4)

site_counts_by_year <- Agashashok_River_Data_filtered %>%
  count(sample_collection_year, SiteID_mod, name = "count_per_year") %>%
  filter(sample_collection_year == "2015")

view(site_counts_by_year)
```

## Plot SiteID by year
```{r}
sampling_count <- 
  ggplot(Agashashok_River_Data_filtered, aes(x = SiteID_mod, y = SiteID_total_count)) +
  geom_point(aes(color = SiteID_mod)) +
  labs(
    title = "Total Sample Count per Site",
    x = "Site ID",
    y = "Total Count"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)  # tilt labels if many sites
  )

sampling_count
```
## Data for plots
```{r}
Agashashok_for_plots <- Agashashok_River_Data_filtered %>%
  filter(SiteID_mod %in% site_counts_by_year$SiteID_mod) %>%
  dplyr::select(ParkID,
                Watershed,
                #Subcatchment,
                #New_Groups,
                #New_Grouping,
                Field_label,
                SiteID_mod,
                SiteID_total_count,
                Latitude,
                Longitude,
                sample_collection_year,
                sample_collection_month,
                sample_collection_season,
                #Watershed_Area,
                #Relative_MS_Watershed_Area,
                SamplingEventID,
                #VisualDescription,
                #Site_Classification,
                #Hyd_Classification,
                #Distance_km,
                #Elevation_ft,
                pH,
                Temp_deg_celsius,
                Diss_oxy_mg_per_l,
                Diss_oxy_percent_sat,
                Spec_Cond_microS_per_cm,
                DIC_mgC_per_l,
                Alk_mgCaCO3_per_l,
                DOC_mgC_per_l,
                f_Cl_mg_per_l,
                f_NO3_mgN_per_l,
                f_SO4_mg_per_l,
                f_Ca_mg_l,
                f_Mg_mg_l,
                f_Na_mg_l,
                f_K_mg_l,
                f_SiO2_mg_per_l,
                f_Pb_mcg_per_l,
f_Ag_mcg_per_l,
f_Al_mcg_per_l,
f_As_mcg_per_l,
f_Ba_mcg_per_l,
#f_Be_mcg_per_l,
f_Cd_mcg_per_l,
f_Ce_mcg_per_l,
f_Co_mcg_per_l,
f_Cr_mcg_per_l,
f_Cu_mcg_per_l,
f_Dy_mcg_per_l,
f_Fe_mcg_per_l,
f_La_mcg_per_l,
f_Mn_mcg_per_l,
f_Nd_mcg_per_l,
f_Ni_mcg_per_l,
f_Pr_mcg_per_l,
f_Se_mcg_per_l,
#f_Th_mcg_per_l,
f_Tl_mcg_per_l,
f_U_mcg_per_l,
f_V_mcg_per_l,
f_Y_mcg_per_l,
f_Zn_mcg_per_l
)

Agashashok_for_plots <- Agashashok_for_plots %>%
  mutate(across(12:50, as.numeric))

view(Agashashok_for_plots)
```

#Temporal Boxplots
## Sulfate
```{r}
sulfate_temporal <- Agashashok_for_plots %>%
ggplot(aes(x = factor(sample_collection_year), y = f_SO4_mg_per_l, fill = sample_collection_season)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  labs(
    title = "Concentration by Year and Season",
    x = "Year",
    y = "Concentration (units)",  # replace with actual units
    fill = "Season"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

sulfate_temporal
```

## pH
```{r}
Mg_temporal <- Agashashok_for_plots %>%
ggplot(aes(x = factor(sample_collection_year), y = pH, fill = sample_collection_season)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  labs(
    title = "Concentration by Year and Season",
    x = "Year",
    y = "Concentration (units)",  # replace with actual units
    fill = "Season"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

Mg_temporal
```

## DIC
```{r}
DIC_temporal <- Agashashok_for_plots %>%
ggplot(aes(x = factor(sample_collection_year), y = DIC_mgC_per_l, fill = sample_collection_season)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  labs(
    title = "Concentration by Year and Season",
    x = "Year",
    y = "Concentration (units)",  # replace with actual units
    fill = "Season"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

DIC_temporal
```

## Alk
```{r}
Alk_temporal <- Agashashok_for_plots %>%
ggplot(aes(x = factor(sample_collection_year), y = Alk_mgCaCO3_per_l, fill = sample_collection_season)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  labs(
    title = "Concentration by Year and Season",
    x = "Year",
    y = "Concentration (units)",  # replace with actual units
    fill = "Season"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

Alk_temporal
```

## Fe
```{r}
Fe_temporal <- Agashashok_for_plots %>%
ggplot(aes(x = factor(sample_collection_year), y = f_Fe_mcg_per_l, fill = sample_collection_season)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  labs(
    title = "Concentration by Year and Season",
    x = "Year",
    y = "Concentration (units)",  # replace with actual units
    fill = "Season"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

Fe_temporal
```

## Ni
```{r}
Cd_temporal <- Agashashok_for_plots %>%
ggplot(aes(x = factor(sample_collection_year), y = f_Cd_mcg_per_l, fill = sample_collection_season)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  labs(
    title = "Concentration by Year and Season",
    x = "Year",
    y = "Concentration (units)",  # replace with actual units
    fill = "Season"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

Cd_temporal
```